name: Generate 3D Contribution Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run 3D Contribution Generator
        run: |
          npx github-contribution-graph --user erickmjr --output profile-3d-contrib

      - name: Commit and push generated files
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add profile-3d-contrib/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update 3D contribution graph"
            git push origin main
          fi
